#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/jq
copy_exec /usr/bin/fido2-token
copy_exec /usr/bin/fido2-assert

mkdir -p "${DESTDIR}/usr/share/fido2-luks"
cp /usr/share/fido2-luks/fido2-luks-keyscript "${DESTDIR}/sbin/fido2-luks-keyscript"
cp /usr/share/fido2-luks/fido2-utils.sh "${DESTDIR}/usr/share/fido2-luks/fido2-utils.sh"

exit 0
