#! /bin/sh
#
# This is /sbin/fido2-keyscript, which gets called when unlocking the disk
#
. /usr/share/fido2-luks/fido2-utils.sh

message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return 0
}

if [ -z "$cryptkeyscript" ]; then
    if [ -x /bin/plymouth ] && plymouth --ping; then
        cryptkeyscript="plymouth ask-for-password --prompt"
    else
        cryptkeyscript="/lib/cryptsetup/askpass"
    fi
fi

# If PIN is not required, we assume that this system is intended to be unlocked
# without needing keyboard interaction, so we wait for 30s for a FIDO2 device
# to show up.
if ! fido2_is_pin_required "$DISK" && ! fido2_device > /dev/null ; then
    message "Waiting up to 30 seconds for FIDO2 device..."
    for i in $(seq 30 -1 1) ; do
        if fido2_device > /dev/null ; then
            break
        fi
        sleep 1
    done
fi

if fido2_device > /dev/null ; then
    if fido2_is_pin_required "$DISK" ; then
        PW="$($cryptkeyscript "Enter the PIN of your FIDO2 token")"
    else
        PW=
    fi
    message "Accessing FIDO2 token..."
    R="$(fido2_authenticate "$PW" "$CRYPTTAB_SOURCE")"
    if [ -z "$R" ]; then
        message "Failed to authenticate using FIDO2 token."
        exit 1
    else
        message "Retrieved the response from token."
        printf '%s' "$R"
        exit 0
    fi
else
    PW="$($cryptkeyscript "Enter a valid disk passphrase, or insert FIDO2 token and press enter")"
    printf '%s' "$PW"
    exit 0
fi
